// For this project development
import '@vue/runtime-core'

// GlobalComponents for Volar
declare module '@vue/runtime-core' {

  export interface GlobalComponents {
    HlAffix: typeof import('../packages/hongluan-ui')['HlAffix']
    HlAlert: typeof import('../packages/hongluan-ui')['HlAlert']
    HlAside: typeof import('../packages/hongluan-ui')['HlAside']
    HlAnchor: typeof import('../packages/hongluan-ui')['HlAnchor']
    HlAnchorLink: typeof import('../packages/hongluan-ui')['HlAnchorLink']
    HlAutocomplete: typeof import('../packages/hongluan-ui')['HlAutocomplete']
    HlThumb: typeof import('../packages/hongluan-ui')['HlThumb']
    HlBacktop: typeof import('../packages/hongluan-ui')['HlBacktop']
    HlBadge: typeof import('../packages/hongluan-ui')['HlBadge']
    HlBreadcrumb: typeof import('../packages/hongluan-ui')['HlBreadcrumb']
    HlBreadcrumbItem: typeof import('../packages/hongluan-ui')['HlBreadcrumbItem']
    HlButton: typeof import('../packages/hongluan-ui')['HlButton']
    HlGroup: typeof import('../packages/hongluan-ui')['HlGroup']
    HlCalendar: typeof import('../packages/hongluan-ui')['HlCalendar']
    HlPanel: typeof import('../packages/hongluan-ui')['HlPanel']
    HlCarousel: typeof import('../packages/hongluan-ui')['HlCarousel']
    HlCarouselItem: typeof import('../packages/hongluan-ui')['HlCarouselItem']
    HlCascader: typeof import('../packages/hongluan-ui')['HlCascader']
    HlCascaderPanel: typeof import('../packages/hongluan-ui')['HlCascaderPanel']
    HlCheckbox: typeof import('../packages/hongluan-ui')['HlCheckbox']
    HlCheckboxGroup: typeof import('../packages/hongluan-ui')['HlCheckboxGroup']
    HlColorPicker: typeof import('../packages/hongluan-ui')['HlColorPicker']
    HlCol: typeof import('../packages/hongluan-ui')['HlCol']
    HlCollapse: typeof import('../packages/hongluan-ui')['HlCollapse']
    HlCollapseItem: typeof import('../packages/hongluan-ui')['HlCollapseItem']
    HlCollapseTransition: typeof import('../packages/hongluan-ui')['HlCollapseTransition']
    HlContainer: typeof import('../packages/hongluan-ui')['HlContainer']
    HlConfigProvider: typeof import('../packages/hongluan-ui')['HlConfigProvider']
    HlDatePicker: typeof import('../packages/hongluan-ui')['HlDatePicker']
    HlDialog: typeof import('../packages/hongluan-ui')['HlDialog']
    HlDropdown: typeof import('../packages/hongluan-ui')['HlDropdown']
    HlDropdownItem: typeof import('../packages/hongluan-ui')['HlDropdownItem']
    HlDropdownMenu: typeof import('../packages/hongluan-ui')['HlDropdownMenu']
    HlFooter: typeof import('../packages/hongluan-ui')['HlFooter']
    HlForm: typeof import('../packages/hongluan-ui')['HlForm']
    HlFormItem: typeof import('../packages/hongluan-ui')['HlFormItem']
    HlHeader: typeof import('../packages/hongluan-ui')['HlHeader']
    HlIcon: typeof import('../packages/hongluan-ui')['HlIcon']
    HlImageViewer: typeof import('../packages/hongluan-ui')['HlImageViewer']
    HlInput: typeof import('../packages/hongluan-ui')['HlInput']
    HlInputNumber: typeof import('../packages/hongluan-ui')['HlInputNumber']
    HlMain: typeof import('../packages/hongluan-ui')['HlMain']
    HlMenu: typeof import('../packages/hongluan-ui')['HlMenu']
    HlMenuItem: typeof import('../packages/hongluan-ui')['HlMenuItem']
    HlMenuItemGroup: typeof import('../packages/hongluan-ui')['HlMenuItemGroup']
    HlOption: typeof import('../packages/hongluan-ui')['HlOption']
    HlOptionGroup: typeof import('../packages/hongluan-ui')['HlOptionGroup']
    HlPagination: typeof import('../packages/hongluan-ui')['HlPagination']
    HlPopper: typeof import('../packages/hongluan-ui')['HlPopper']
    HlPopover: typeof import('../packages/hongluan-ui')['HlPopover']
    HlProgress: typeof import('../packages/hongluan-ui')['HlProgress']
    HlRadio: typeof import('../packages/hongluan-ui')['HlRadio']
    HlRadioGroup: typeof import('../packages/hongluan-ui')['HlRadioGroup']
    HlRow: typeof import('../packages/hongluan-ui')['HlRow']
    HlScrollbar: typeof import('../packages/hongluan-ui')['HlScrollbar']
    HlSelect: typeof import('../packages/hongluan-ui')['HlSelect']
    HlSlider: typeof import('../packages/hongluan-ui')['HlSlider']
    HlStep: typeof import('../packages/hongluan-ui')['HlStep']
    HlSteps: typeof import('../packages/hongluan-ui')['HlSteps']
    HlSkeleton: typeof import('../packages/hongluan-ui')['HlSkeleton']
    HlSkeletonItem: typeof import('../packages/hongluan-ui')['HlSkeletonItem']
    HlSubMenu: typeof import('../packages/hongluan-ui')['HlSubMenu']
    HlSwitch: typeof import('../packages/hongluan-ui')['HlSwitch']
    HlSpinner: typeof import('../packages/hongluan-ui')['HlSpinner']
    HlSubHeader: typeof import('../packages/hongluan-ui')['HlSubHeader']
    HlTabPane: typeof import('../packages/hongluan-ui')['HlTabPane']
    HlTable: typeof import('../packages/hongluan-ui')['HlTable']
    HlTableColumn: typeof import('../packages/hongluan-ui')['HlTableColumn']
    HlTabs: typeof import('../packages/hongluan-ui')['HlTabs']
    HlTag: typeof import('../packages/hongluan-ui')['HlTag']
    HlTimePicker: typeof import('../packages/hongluan-ui')['HlTimePicker']
    HlTimeline: typeof import('../packages/hongluan-ui')['HlTimeline']
    HlTimelineItem: typeof import('../packages/hongluan-ui')['HlTimelineItem']
    HlTimeSelect: typeof import('../packages/hongluan-ui')['HlTimeSelect']
    HlTooltip: typeof import('../packages/hongluan-ui')['HlTooltip']
    HlTransfer: typeof import('../packages/hongluan-ui')['HlTransfer']
    HlTree: typeof import('../packages/hongluan-ui')['HlTree']
    HlTreeV2: typeof import('../packages/hongluan-ui')['HlTreeV2']
    HlUpload: typeof import('../packages/hongluan-ui')['HlUpload']
    HlSelectV2: typeof import('../packages/hongluan-ui')['HlSelectV2']
    HlSelector: typeof import('../packages/hongluan-ui')['HlSelector']
    HlLayout: typeof import('../packages/hongluan-ui')['HlLayout']
    HlList: typeof import('../packages/hongluan-ui')['HlList']
    HlLink: typeof import('../packages/hongluan-ui')['HlLink']
    HlListItem: typeof import('../packages/hongluan-ui')['HlListItem']
    HlSimpleTable: typeof import('../packages/hongluan-ui')['HlSimpleTable']
    HlVirtualTable: typeof import('../packages/hongluan-ui')['HlVirtualTable']
  }

  interface ComponentCustomProperties {
    $message: typeof import('../packages/hongluan-ui')['HlMessage']
    $notify: typeof import('../packages/hongluan-ui')['HlNotification']
    $msgbox: typeof import('../packages/hongluan-ui')['HlMessageBox']
    $messageBox: typeof import('../packages/hongluan-ui')['HlMessageBox']
    $alert: typeof import('../packages/hongluan-ui')['HlMessageBox']['alert']
    $confirm: typeof import('../packages/hongluan-ui')['HlMessageBox']['confirm']
    $loading: typeof import('../packages/hongluan-ui')['HlLoadingService']
  }
}

export {}
