<template>
  <hl-thumb
    size="xxxs"
    fit="cover"
    class="m-r-md"
    src="https://pimg.39.net/yaopin/zycimg/11hxcu4pth3wu2019.jpg"
  />
  <hl-thumb
    size="xxs"
    fit="cover"
    class="m-r-md"
    src="https://pimg.39.net/yaopin/zycimg/11hxcu4pth3wu2019.jpg"
  />
  <hl-thumb
    size="xs"
    fit="cover"
    class="m-r-md"
    src="https://pimg.39.net/yaopin/zycimg/11hxcu4pth3wu2019.jpg"
  />
  <hl-thumb
    size="sm"
    fit="cover"
    class="m-r-md"
    src="https://pimg.39.net/yaopin/zycimg/11hxcu4pth3wu2019.jpg"
  />
  <hl-thumb
    size="md"
    fit="cover"
    class="m-r-md"
    src="https://pimg.39.net/yaopin/zycimg/11hxcu4pth3wu2019.jpg"
  />
  <hl-thumb
    size="lg"
    fit="cover"
    class="m-r-md"
    src="https://pimg.39.net/yaopin/zycimg/11hxcu4pth3wu2019.jpg"
  />
  <hl-thumb
    size="xl"
    fit="cover"
    class="m-r-md"
    src="https://pimg.39.net/yaopin/zycimg/11hxcu4pth3wu2019.jpg"
  />
  <hl-thumb
    size="xxl"
    fit="cover"
    class="m-r-md"
    src="https://pimg.39.net/yaopin/zycimg/11hxcu4pth3wu2019.jpg"
  />
  <hl-thumb
    size="xxxl"
    fit="cover"
    class="m-r-md"
    src="https://pimg.39.net/yaopin/zycimg/11hxcu4pth3wu2019.jpg"
  />
</template>
